import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import http from 'node:http';
import path from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';

const html=`<!doctype html><html data-pink-mod-test><meta charset="utf-8"><style>:root{--color-background-primary-soft:#fff7f8;--color-background-control:#fff7f8;--color-background-elevated-primary:#fff9fa;--color-border-primary-outline:#e4cbd5}*{box-sizing:border-box}body{margin:0;font:14px 'Segoe UI',sans-serif}main{min-height:330px;padding:35px;border-left:1px solid transparent}.rail{padding:10px 14px;border:1px solid var(--color-border-primary-outline);border-radius:18px 18px 0 0;display:flex;justify-content:space-between;gap:20px;background:color-mix(in srgb,var(--color-background-primary-soft) 70%,transparent)}button{font:inherit;color:inherit;border:0;background:transparent;cursor:pointer}.compose{height:65px;border-radius:18px;background:var(--color-background-control);margin-top:-1px}.chips{display:flex;gap:16px;margin-top:50px}.chip{padding:10px 14px;border:1px solid var(--color-border-primary-outline);border-radius:18px;background:var(--color-background-primary-soft)}.control{background:var(--color-background-control)}.elevated{background:var(--color-background-elevated-primary)}.added{color:#00a240}.removed{color:#e02e2a}.warning{background:#ffe7d9}</style><body><main class="main-surface"><div data-composer-rail><div class="rail" data-composer-rail-item="present" data-composer-rail-variant="default"><span>Уточнение к задаче</span><button>↪ Скорректировать　♲　•••</button></div></div><div class="compose"></div><div class="chips"><button class="chip">Изменён 1 файл <span class="added">+6</span> <span class="removed">−1</span></button><button class="chip control">Файлы</button><button class="chip elevated">Сводка</button></div><div class="warning" data-composer-rail-item="present" data-composer-rail-variant="warning" hidden>Warning fixture</div></main></body></html>`;
test('queue and summary surfaces follow every preset without recoloring diff counters',async()=>{
 const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_PATH||path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs')));
 const source=await fs.readFile(new URL('../plugins/pink-glass/payload/renderer.js',import.meta.url),'utf8');const out=new URL('./assets/auxiliary-palette/',import.meta.url);await fs.mkdir(out,{recursive:true});
 const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});
 try{for(const theme of ['sakura','lavender','moonlight','peach','mint']){
  const page=await browser.newPage({viewport:{width:850,height:330}});await page.goto(`http://127.0.0.1:${server.address().port}`);const saved=JSON.stringify({version:1,active:theme,themes:{}});await page.evaluate(s=>localStorage.setItem('codex-pink-mod:profiles:v1',s),saved);const width=(await page.locator('.rail').boundingBox()).width;await page.evaluate(source);
  const values=await page.evaluate(()=>{const rgb=h=>'rgb('+[1,3,5].map(i=>parseInt(h.trim().slice(i,i+2),16)).join(', ')+')';const config=getComputedStyle(document.getElementById('codex-pink-mod')),s=x=>getComputedStyle(document.querySelector(x));return {panel:rgb(config.getPropertyValue('--editor-panel')),card:rgb(config.getPropertyValue('--editor-card')),border:rgb(config.getPropertyValue('--editor-border')),chip:s('.chip').backgroundColor,control:s('.control').backgroundColor,elevated:s('.elevated').backgroundColor,edge:s('.chip').borderColor,added:s('.added').color,removed:s('.removed').color,warning:s('.warning').backgroundColor,rail:s('.rail').backgroundColor}});
  assert.equal(values.chip,values.panel);assert.equal(values.control,values.card);assert.equal(values.elevated,values.card);assert.equal(values.edge,values.border);assert.equal(values.added,'rgb(0, 162, 64)');assert.equal(values.removed,'rgb(224, 46, 42)');assert.equal(values.warning,'rgb(255, 231, 217)');assert.ok(values.rail.includes('0.96'));assert.equal((await page.locator('.rail').boundingBox()).width,width);assert.equal(await page.evaluate(()=>localStorage.getItem('codex-pink-mod:profiles:v1')),saved);
  await page.screenshot({path:fileURLToPath(new URL(`${theme}.png`,out))});await page.evaluate(()=>window.__CODEX_PINK_MOD__.cleanup());assert.equal(await page.locator('.chip').first().evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 247, 248)');await page.close();console.log(theme+': themed neutral surfaces; diff and warning colors preserved');
 }}finally{await browser.close();await new Promise(r=>server.close(r))}
});
