import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import {pathToFileURL,fileURLToPath} from 'node:url';

const html=`<!doctype html><html data-pink-mod-test><meta charset="utf-8"><style>
:root{--color-chart-blue:#e4cbd5;--color-text:#503d4b;--color-background-button-primary:#503d4b;--color-background-button-primary-hover:#876978;--color-text-button-primary:white;--color-background-button-secondary:#f6e7ed;--color-text-button-secondary:#503d4b;--color-background-button-secondary-hover:#e4cbd5;--color-background-button-secondary-active:#d8b6c6;--color-background-mode-toggle-track:#f2e7ea;--color-background-mode-toggle-selected:#fff7f8;--color-border-mode-toggle-selected:#e4cbd5;--gray-0:#fff;--color-accent-red:#e02e2a;--color-accent-green:#00a240;--color-accent-yellow:#ffc300}
*{box-sizing:border-box}body{margin:0;display:flex;height:620px;font:15px 'Segoe UI',sans-serif}aside{width:230px;padding:24px}main{flex:1;padding:28px}h1{font-size:22px}.row{display:flex;gap:14px;align-items:center;margin:20px 0}.panel{padding:18px;background:var(--color-surface-tertiary);border-radius:16px}button{font:inherit;border:0;padding:8px 12px;cursor:pointer;border-radius:10px;color:inherit}button:disabled{opacity:.4;cursor:default}.bg-chart-blue{background-color:var(--color-chart-blue)}.update{font-weight:500;height:20px;border-radius:20px;font-size:10px;padding:0 11px}.update:hover{background:color-mix(in srgb,var(--color-chart-blue) 92%,black 8%)}.update:active{background:color-mix(in srgb,var(--color-chart-blue) 80%,transparent)}.download{width:20px;padding:0}.primary{background:var(--color-background-button-primary);color:var(--color-text-button-primary)}.primary:hover{background:var(--color-background-button-primary-hover)}.secondary{background:var(--color-background-button-secondary);color:var(--color-text-button-secondary)}.secondary:hover{background:var(--color-background-button-secondary-hover)}.secondary:active{background:var(--color-background-button-secondary-active)}[role=switch]{padding:4px;background:transparent}.track{display:flex;align-items:center;width:36px;height:22px;border-radius:22px}.thumb{width:18px;height:18px;border-radius:50%;background:var(--gray-0);border:1px solid var(--gray-0);transform:translateX(2px)}.thumb[data-state=checked]{transform:translateX(16px)}.bg-text{background:var(--color-text)}[class~="bg-text/10"]{background:color-mix(in srgb,var(--color-text) 10%,transparent)}.mode{background:var(--color-background-mode-toggle-track);padding:4px;border-radius:12px}.selected{background:var(--color-background-mode-toggle-selected);border:1px solid var(--color-border-mode-toggle-selected)}input[type=range]{width:230px}.chart{width:24px;height:24px}.added{color:var(--color-accent-green)}.removed{color:var(--color-accent-red)}.warning{color:var(--color-accent-yellow)}
</style><body><aside class="app-shell-left-panel"><h1>Обновление</h1><div class="row"><button id="update" class="update no-drag bg-chart-blue contain-layout contain-style" aria-label="Обновить" title="Обновить">Обновить</button><button id="download" class="download update no-drag bg-chart-blue contain-layout contain-style" aria-label="Скачать обновление" title="Скачать обновление">↓</button></div></aside><main class="main-surface"><h1>Элементы управления</h1><div class="panel"><div class="row"><button class="primary">Сохранить</button><button class="secondary">Настроить</button><button class="secondary" disabled>Недоступно</button></div><div class="row"><span>Включено</span><button id="toggle" role="switch" aria-checked="true" data-state="checked"><span aria-hidden="true" data-state="checked" class="track bg-chart-blue"><span class="thumb" data-state="checked"></span></span></button><span>Выключено</span><button id="off" role="switch" aria-checked="false" data-state="unchecked"><span aria-hidden="true" data-state="unchecked" class="track bg-text/10"><span class="thumb" data-state="unchecked"></span></span></button><button id="disabled" role="switch" aria-checked="true" data-state="checked" disabled><span aria-hidden="true" data-state="checked" class="track bg-chart-blue"><span class="thumb" data-state="checked"></span></span></button></div><div class="row"><input type="checkbox" checked aria-label="Флажок"><input type="radio" checked aria-label="Выбор"><input type="range" min="0" max="100" value="40" aria-label="Ползунок"></div><div class="row mode"><button class="selected">Выбрано</button><button>Другой режим</button></div><div class="row"><span>Проверка независимых цветов:</span><div id="chart" class="chart bg-chart-blue"></div><span class="added">+6</span><span class="removed">−1</span><span class="warning">!</span></div></div></main></body></html>`;
const luminance=rgb=>rgb.slice(0,3).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0);
const contrast=(a,b)=>(Math.max(luminance(a),luminance(b))+.05)/(Math.min(luminance(a),luminance(b))+.05);

test('all control palettes and interaction states follow the theme without recoloring charts/statuses',async()=>{
 const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_PATH||path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs')));
 const source=await fs.readFile(new URL('../plugins/pink-glass/payload/renderer.js',import.meta.url),'utf8');const out=new URL('./assets/control-palette/',import.meta.url);await fs.mkdir(out,{recursive:true});
 const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});
 try{for(const theme of ['sakura','lavender','moonlight','peach','mint']){
  const page=await browser.newPage({viewport:{width:1020,height:620}});await page.goto(`http://127.0.0.1:${server.address().port}`);const saved=JSON.stringify({version:1,active:theme,themes:{}});await page.evaluate(saved=>localStorage.setItem('codex-pink-mod:profiles:v1',saved),saved);const before=await page.locator('#update').boundingBox();
  await page.evaluate(()=>{document.querySelector('#toggle').onclick=e=>{const button=e.currentTarget,next=button.getAttribute('aria-checked')!=='true';button.setAttribute('aria-checked',String(next));button.dataset.state=next?'checked':'unchecked';const track=button.firstElementChild;track.dataset.state=button.dataset.state;track.className='track '+(next?'bg-chart-blue':'bg-text/10');track.firstElementChild.dataset.state=button.dataset.state;};});
  await page.evaluate(source);
  const sample=()=>page.evaluate(()=>{const s=x=>getComputedStyle(document.querySelector(x));const rgba=color=>{const c=document.createElement('canvas');c.width=c.height=1;const x=c.getContext('2d');x.fillStyle=color;x.fillRect(0,0,1,1);return [...x.getImageData(0,0,1,1).data]};const editor=getComputedStyle(document.getElementById('codex-pink-mod'));return{updateBg:rgba(s('#update').backgroundColor),updateInk:rgba(s('#update').color),downloadBg:rgba(s('#download').backgroundColor),track:rgba(s('#toggle>.track').backgroundColor),off:rgba(s('#off>.track').backgroundColor),thumb:s('#toggle .thumb').backgroundColor,transform:s('#toggle .thumb').transform,accent:rgba(editor.getPropertyValue('--editor-accent')),panel:rgba(editor.getPropertyValue('--editor-panel')),card:rgba(editor.getPropertyValue('--editor-card')),secondary:rgba(s('.secondary').backgroundColor),selected:rgba(s('.selected').backgroundColor),range:rgba(s('input[type=range]').accentColor),checkbox:rgba(s('input[type=checkbox]').accentColor),radio:rgba(s('input[type=radio]').accentColor),disabled:s('#disabled').opacity,chart:s('#chart').backgroundColor,statuses:['.added','.removed','.warning'].map(x=>s(x).color)}});
  const normal=await sample();assert.deepEqual(normal.track,normal.accent);assert.deepEqual(normal.updateBg,normal.downloadBg);assert.ok(contrast(normal.updateBg,normal.updateInk)>=4.5,`${theme}: update text contrast`);assert.deepEqual(normal.secondary,normal.panel);assert.deepEqual(normal.selected,normal.card);assert.deepEqual(normal.range,normal.accent);assert.deepEqual(normal.checkbox,normal.accent);assert.deepEqual(normal.radio,normal.accent);assert.equal(normal.thumb,'rgb(255, 255, 255)');assert.equal(normal.disabled,'0.4');assert.ok(normal.off[3]>=25&&normal.off[3]<=26);assert.equal(normal.chart,'rgb(228, 203, 213)');assert.deepEqual(normal.statuses,['rgb(0, 162, 64)','rgb(224, 46, 42)','rgb(255, 195, 0)']);
  const after=await page.locator('#update').boundingBox();assert.equal(after.width,before.width);assert.equal(after.height,before.height);
  await page.locator('#update').hover();const hovered=await sample();assert.notDeepEqual(hovered.updateBg,normal.updateBg);assert.ok(contrast(hovered.updateBg,hovered.updateInk)>=4.5);await page.mouse.down();const pressed=await sample();assert.notDeepEqual(pressed.updateBg,hovered.updateBg);assert.equal(pressed.updateBg[3],255,'Pressed fill must stay opaque');assert.ok(contrast(pressed.updateBg,pressed.updateInk)>=4.5,'Pressed label remains readable');await page.mouse.up();
  await page.locator('#toggle').click();assert.equal(await page.locator('#toggle').getAttribute('aria-checked'),'false');assert.notEqual((await sample()).transform,normal.transform);await page.locator('#toggle').click();assert.deepEqual((await sample()).track,normal.track);assert.ok(await page.locator('#disabled').isDisabled());await page.getByRole('slider',{name:'Ползунок'}).fill('75');assert.equal(await page.getByRole('slider',{name:'Ползунок'}).inputValue(),'75');
  await page.mouse.move(1000,610);await page.screenshot({path:fileURLToPath(new URL(theme+'.png',out))});assert.equal(await page.evaluate(()=>localStorage.getItem('codex-pink-mod:profiles:v1')),saved);await page.evaluate(()=>window.__CODEX_PINK_MOD__.cleanup());assert.equal(await page.locator('#update').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(228, 203, 213)');await page.close();console.log(theme+': update/download, toggles, range, radio, checkbox, hover/press, disabled, charts/statuses passed');
 }}finally{await browser.close();await new Promise(r=>server.close(r))}
});
