import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import http from 'node:http';
import {pathToFileURL,fileURLToPath} from 'node:url';

const html=`<!doctype html><html data-pink-mod-test><meta charset="utf-8"><style>*{box-sizing:border-box}body{margin:0;font:15px 'Segoe UI',sans-serif}main{min-height:430px;padding:42px;border-left:1px solid transparent}.example{max-width:700px;margin:0 auto 38px}.rail{position:relative;margin:0 12px;overflow:clip;border-color:#e4cbd5;border-radius:22px 22px 0 0;corner-shape:superellipse(1.5)}.rail::after{content:"";position:absolute;inset:0;pointer-events:none;border-style:solid;border-width:1px 1px 0;border-color:inherit;border-radius:inherit;corner-shape:inherit;opacity:0}.item{border:1px solid #e4cbd5;border-radius:0;background:#fffafb;padding:11px 14px;overflow:clip}.body{height:80px;border-radius:22px;background:var(--color-surface-tertiary);box-shadow:inset 0 0 0 1px var(--color-border)}.label{font-size:12px;margin:0 0 10px}</style><body><main class="main-surface"><div class="example" data-codex-composer-root data-composer-placement="home"><div class="label">Прямой дочерний элемент</div><div id="direct" class="rail _attached_test" data-composer-rail data-composer-rail-placement="above"><div class="item" data-composer-placement="home" data-composer-rail-item="present" data-composer-rail-variant="controls">▢ Выбрать проект　　Локальный　　main</div></div><div class="body"></div></div><div class="example" data-codex-composer-root data-composer-placement="home"><div class="label">Полоска во внутреннем контейнере</div><div id="wrapped" class="rail _attached_test" data-composer-rail data-composer-rail-placement="above"><div class="_target_test"><div class="item" data-composer-placement="home" data-composer-rail-item="present" data-composer-rail-variant="controls">▢ Выбрать проект</div></div></div><div class="body"></div></div></main></body></html>`;
test('home rail outline follows native rounded parent instead of clipped square child',async()=>{
 const {chromium}=await import(pathToFileURL(process.env.PLAYWRIGHT_PATH||path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs')));
 const source=await fs.readFile(new URL('../plugins/pink-glass/payload/renderer.js',import.meta.url),'utf8');const out=new URL('./assets/rail-corner/',import.meta.url);await fs.mkdir(out,{recursive:true});
 const server=http.createServer((req,res)=>{res.setHeader('Content-Type','text/html;charset=utf-8');res.end(html)});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});
 try{for(const theme of ['sakura','lavender','moonlight','peach','mint']){
  const page=await browser.newPage({viewport:{width:800,height:430}});await page.goto(`http://127.0.0.1:${server.address().port}`);const original=await page.locator('#direct').boundingBox();await page.evaluate(theme=>localStorage.setItem('codex-pink-mod:profiles:v1',JSON.stringify({version:1,active:theme,themes:{}})),theme);await page.evaluate(source);
  for(const id of ['direct','wrapped']){
   const value=await page.locator('#'+id).evaluate(e=>{const s=getComputedStyle(e),p=getComputedStyle(e,'::after'),c=getComputedStyle(e.querySelector('.item'));return{opacity:p.opacity,radius:p.borderRadius,parentRadius:s.borderRadius,shape:p.getPropertyValue('corner-shape'),parentShape:s.getPropertyValue('corner-shape'),color:p.borderColor,parentColor:s.borderColor,width:p.borderWidth,pointer:p.pointerEvents,childColor:c.borderColor,childWidth:c.borderWidth}});
   assert.equal(value.opacity,'1');assert.equal(value.radius,value.parentRadius);assert.equal(value.shape,value.parentShape);assert.equal(value.color,value.parentColor);assert.equal(value.width,'1px 1px 0px');assert.equal(value.pointer,'none');assert.equal(value.childColor,'rgba(0, 0, 0, 0)');assert.equal(value.childWidth,'1px');
  }
  const rect=await page.locator('#direct').boundingBox();assert.equal(rect.width,original.width);assert.equal(rect.height,original.height);await page.screenshot({path:fileURLToPath(new URL(theme+'.png',out))});
  await page.locator('#direct .item').evaluate(e=>e.setAttribute('aria-hidden','true'));assert.equal(await page.locator('#direct').evaluate(e=>getComputedStyle(e,'::after').opacity),'0','Hidden controls must not leave a ghost outline');
  await page.evaluate(()=>window.__CODEX_PINK_MOD__.cleanup());assert.equal(await page.locator('#wrapped').evaluate(e=>getComputedStyle(e,'::after').opacity),'0');await page.close();console.log(theme+': direct/wrapped rounded outline, unchanged dimensions and hidden state passed');
 }}finally{await browser.close();await new Promise(r=>server.close(r))}
});
