import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import http from 'node:http';
import { pathToFileURL, fileURLToPath } from 'node:url';
import path from 'node:path';

test('theme can be toggled off and on without losing the editor', async () => {
  const packagePath = process.env.PLAYWRIGHT_PATH || path.join(process.env.USERPROFILE, '.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs');
  const { chromium } = await import(pathToFileURL(packagePath));
  const source = await fs.readFile(new URL('../plugins/pink-glass/payload/renderer.js', import.meta.url), 'utf8');
  const server = http.createServer((req, res) => {
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.end('<!doctype html><html data-pink-mod-test><head><style>main{background:rgb(255,255,255)}body{margin:0;display:flex;height:100vh;font:16px sans-serif}aside{width:240px}main{flex:1;padding:30px}.composer-surface-chrome{padding:24px}</style></head><body><aside class="app-shell-left-panel">Проекты</aside><main class="main-surface"><h1>Тестовая оболочка</h1><p>Проверка оформления</p><div data-local-conversation-user-anchor><div class="bg-user-message">Сообщение</div></div><div data-codex-composer-root class="composer-surface-chrome"><button aria-label="Отправить">↑</button></div></main></body></html>');
  });
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1100, height: 850 } });
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await page.goto(`http://127.0.0.1:${server.address().port}`);
    const original = await page.locator('main').evaluate(el => getComputedStyle(el).backgroundColor);
    await page.evaluate(source);
    await page.evaluate(source);
    assert.equal(await page.locator('#codex-pink-mod').count(), 1);
    assert.equal(await page.locator('#codex-pink-mod-style').count(), 1);
    assert.equal(await page.locator('main').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(255, 245, 247)');
    assert.equal(await page.locator('main').evaluate(el => getComputedStyle(el).backgroundImage.includes('data:image/webp;base64,')), true);
    assert.equal(await page.locator('aside').evaluate(el => getComputedStyle(el).backdropFilter), 'blur(10px)');
    await page.getByRole('button', { name: 'Открыть редактор темы' }).click();
    assert.equal(await page.getByRole('dialog').isVisible(), true);
    assert.equal(await page.getByText('Розовое стекло', {exact:true}).count(), 0);
    const enabled = page.getByRole('checkbox', {name:'Тема включена'});
    await enabled.uncheck();
    await page.waitForFunction(() => document.getElementById('codex-pink-mod-style').textContent === '');
    assert.equal(await page.getByRole('dialog').isVisible(), true);
    await enabled.check();
    await page.waitForFunction(() => document.getElementById('codex-pink-mod-style').textContent.length > 0);
    const dim=page.getByRole('slider',{name:'Приглушить фон слева',exact:true});
    assert.equal(await dim.inputValue(),'0');
    const mainBackground=await page.locator('main').evaluate(e=>getComputedStyle(e).backgroundImage);
    const textColor=await page.locator('aside').evaluate(e=>getComputedStyle(e).color);
    await dim.fill('100');
    await page.waitForFunction(()=>getComputedStyle(document.querySelector('aside')).boxShadow.includes('rgb(246, 231, 237)'));
    assert.equal(await page.locator('main').evaluate(e=>getComputedStyle(e).backgroundImage),mainBackground);
    assert.equal(await page.locator('aside').evaluate(e=>getComputedStyle(e).color),textColor);
    await page.getByRole('button',{name:'Сохранить',exact:true}).click();
    assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('codex-pink-mod:profiles:v1')).themes.sakura.sidebarDim),100);
    await page.getByText('Стекло и прозрачность', {exact:true}).click();
    const blur=page.getByRole('slider',{name:'Размытие стекла',exact:true});
    await blur.fill('5');
    await page.getByRole('button',{name:'Сохранить',exact:true}).click();
    assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('codex-pink-mod:profiles:v1')).themes.sakura.glassBlur),5);
    await page.getByRole('button',{name:'Сбросить настройки темы',exact:true}).click();
    await page.getByRole('button',{name:'Сохранить',exact:true}).click();
    const preset=JSON.parse(await fs.readFile(new URL('./fixtures/sakura.json',import.meta.url),'utf8'));
    assert.deepEqual({...preset,...await page.evaluate(()=>JSON.parse(localStorage.getItem('codex-pink-mod:profiles:v1')).themes.sakura)},{...preset,wallpaperTint:false,sidebarDim:0,wallpaperTintStrength:25});
    await page.getByText('Цвета', {exact:true}).click();
    await page.getByRole('textbox', {name:'Фон чата HEX',exact:true}).fill('#f9f5ff');
    await page.getByRole('button', {name:'Сохранить',exact:true}).click();
    assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('codex-pink-mod:profiles:v1')).themes.sakura.bg), '#f9f5ff');
    await page.getByRole('combobox',{name:'Выбрать тему'}).selectOption('lavender');
    assert.equal(await page.getByRole('textbox',{name:'Фон чата HEX',exact:true}).inputValue(),'#f4f0fa');
    await page.getByRole('textbox',{name:'Фон чата HEX',exact:true}).fill('#eae0ff');
    await page.getByRole('combobox',{name:'Выбрать тему'}).selectOption('sakura');
    assert.equal(await page.getByRole('textbox',{name:'Фон чата HEX',exact:true}).inputValue(),'#f9f5ff');
    await page.getByRole('combobox',{name:'Выбрать тему'}).selectOption('lavender');
    assert.equal(await page.getByRole('textbox',{name:'Фон чата HEX',exact:true}).inputValue(),'#eae0ff');
    await page.reload();await page.evaluate(source);
    await page.getByRole('button',{name:'Открыть редактор темы'}).click();
    assert.equal(await page.getByRole('combobox',{name:'Выбрать тему'}).inputValue(),'lavender');
    await page.getByRole('button',{name:'Сбросить настройки темы',exact:true}).click();
    await page.getByRole('combobox',{name:'Выбрать тему'}).selectOption('sakura');
    await page.getByText('Цвета',{exact:true}).click();
    assert.equal(await page.getByRole('textbox',{name:'Фон чата HEX',exact:true}).inputValue(),'#f9f5ff');
    for (const id of ['moonlight','peach','mint']) {
      await page.getByRole('combobox',{name:'Выбрать тему'}).selectOption(id);
      await page.getByRole('button',{name:'Сохранить',exact:true}).click();
      assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('codex-pink-mod:profiles:v1')).active),id);
      assert.equal(await page.evaluate(async()=>{const im=document.getElementById('codex-pink-mod').shadowRoot.querySelector('[data-preview="wallpaper"]');await im.decode();return im.naturalWidth>1000;}),true);
      assert.equal(await page.locator('main').evaluate(e=>getComputedStyle(e).backgroundImage.includes('data:image/png')),true);
      assert.equal(await page.locator('html').evaluate(e=>getComputedStyle(e).colorScheme),id==='moonlight'?'dark':'light');
      assert.ok(await page.evaluate(()=>localStorage.getItem('codex-pink-mod:profiles:v1').length)<15000);
      await page.reload();await page.evaluate(source);
      await page.getByRole('button',{name:'Открыть редактор темы',exact:true}).click();
      assert.equal(await page.getByRole('combobox',{name:'Выбрать тему'}).inputValue(),id);
      assert.equal(await page.locator('main').evaluate(e=>getComputedStyle(e).backgroundImage.includes('data:image/png')),true);
      await page.screenshot({path:fileURLToPath(new URL('./assets/'+id+'-ui-check.png',import.meta.url))});
    }
    await page.getByRole('combobox',{name:'Выбрать тему'}).selectOption('sakura');
    await page.evaluate(() => localStorage.removeItem('codex-pink-mod:profiles:v1'));
    await page.evaluate(() => localStorage.setItem('codex-pink-mod:v1', JSON.stringify({enabled:true,glass:false,bg:'#f9f5ff'})));
    await page.reload();
    await page.evaluate(source);
    assert.equal(await page.locator('main').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(249, 245, 255)');
    assert.equal(await page.locator('aside').evaluate(el => getComputedStyle(el).backdropFilter), 'blur(10px)');
    assert.equal(await page.locator('#codex-pink-mod').count(), 1);
    await page.evaluate(() => window.__CODEX_PINK_MOD__.cleanup());
    assert.equal(await page.locator('#codex-pink-mod-style').count(), 0);
    assert.equal(await page.locator('main').evaluate(el => getComputedStyle(el).backgroundColor), original);
    assert.deepEqual(errors, []);
  } finally { await browser.close(); await new Promise(resolve => server.close(resolve)); }
});
